services:
  arcus:
    privileged: true
    build: .
    container_name: arcus
    volumes:
      - ../sim_ws/src/f1tenth_gym:/sim_ws/src/f1tenth_gym
      - ../sim_ws/src/f1tenth_gym_ros:/sim_ws/src/f1tenth_gym_ros
      - ../sim_ws/src/fake_imu:/sim_ws/src/fake_imu
      - ../sim_ws/src/scripts:/sim_ws/src/scripts
      - ../sim_ws/src/visualization:/sim_ws/src/visualization
      - ../sim_ws/src/arcus_gui:/sim_ws/src/arcus_gui
      - ../../arcus:/sim_ws/src/arcus
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/nsswitch.conf:/etc/nsswitch.conf:ro
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    environment:
      - DISPLAY=${DISPLAY}
      - MPLBACKEND=TkAgg
      - MESA_GL_VERSION_OVERRIDE=3.3
      - MESA_GLSL_VERSION_OVERRIDE=330
      - ROS_DOMAIN_ID=42
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - "CYCLONEDDS_URI=<CycloneDDS><Domain><General><Interfaces><NetworkInterface name=\"wlp0s20f3\"/></Interfaces></General></Domain></CycloneDDS>"

    network_mode: host
    stdin_open: true
    tty: true

    working_dir: /sim_ws

