services:
  arcus:
    build: .
    container_name: arcus
    volumes:
      - ../sim_ws/src/f1tenth_gym:/sim_ws/src/f1tenth_gym
      - ../sim_ws/src/f1tenth_gym_ros:/sim_ws/src/f1tenth_gym_ros
      - ../sim_ws/src/fake_imu:/sim_ws/src/fake_imu
      - ../sim_ws/src/scripts:/sim_ws/src/scripts
      - ../sim_ws/src/visualization:/sim_ws/src/visualization
      - ../sim_ws/src/arcus_gui:/sim_ws/src/arcus_gui
      - ../../arcus:/sim_ws/src/arcus
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY=${DISPLAY}
      - MESA_GL_VERSION_OVERRIDE=3.3
      - MESA_GLSL_VERSION_OVERRIDE=330

    network_mode: host
    stdin_open: true
    tty: true

    working_dir: /sim_ws
