name: Test Docker build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-docker-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: test-image
          labels: |
            org.opencontainers.image.description=Test build for arcus-simulation

      - name: Build Docker image (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: sim_ws/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

